---
# playbooks/create_droplet_from_snapshot.yml

- name: Create a Droplet from a Snapshot in a Specific Team
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - secrets.yml

  vars:
    # Name your droplet however you like
    droplet_name: my-snapshot-droplet-5

    # Choose your region and size slugs
    region: nyc3
    size: s-2vcpu-4gb

    # The snapshot identifier (UUID or slug)
    snapshot_id: "207695890"

    # Point this at a token that has access to your target team
    do_team_token: "{{ DIGITALOCEAN_TOKEN }}"

  tasks:
    - name: Create Droplet from Snapshot
      # Tell the module to use your team token via the env var
      community.digitalocean.digital_ocean_droplet:
        api_token: "{{ do_team_token }}"
        name: "{{ droplet_name }}"
        region: "{{ region }}"
        size: "{{ size }}"
        image: "{{ snapshot_id }}"
        ssh_keys: ['48536093']
        unique_name: true
        timeout: 500
        user_data: |  
          #cloud-config
          runcmd:
            - [ sh, -c, "hostnamectl set-hostname {{ droplet_name }}" ]
            - [ "sh", "-c", "DBPASS=\"$(openssl rand -hex 12)\"; DBNAME=\"db_$(tr -dc 'a-z0-9' </dev/urandom | head -c6)\"; DBUSER=\"user_$(tr -dc 'a-z0-9' </dev/urandom | head -c6)\"; echo \"Generated DBNAME DBUSER DB_PASSWORD \"; SQL=\"CREATE DATABASE IF NOT EXISTS \\`${DBNAME}\\`; CREATE USER IF NOT EXISTS '${DBUSER}'@'%' IDENTIFIED BY '${DBPASS}'; GRANT ALL PRIVILEGES ON \\`${DBNAME}\\`.* TO '${DBUSER}'@'%'; FLUSH PRIVILEGES;\"; mysql --execute=\"$SQL\"; printf 'DB_PASSWORD=%s\nDB_NAME=%s\nDB_USER=%s\n' \"$DBPASS\" \"$DBNAME\" \"$DBUSER\" > /root/mysql.txt; chmod 600 /root/mysql.txt; echo \"DB created and credentials written to /root/mysql.txt\"" ]
            - [ sh, -c, "set -eu; curl -L https://gist.githubusercontent.com/ukedotsh/08c0e624440f0d7afb70523d5c07d8e3/raw/6a169402a20b3ba64c89081a162eb94508072ba9/seed-install.sh -o /var/www/vhosts/staging/seed-install.sh && chmod +x /var/www/vhosts/staging/seed-install.sh; curl -L https://gist.githubusercontent.com/ukedotsh/d603ece3c02e60ad81fa351a5a2c15ad/raw/09e51aafa7b683efc623d12ce5712044534eaf1c/seed-config.sh -o /var/www/vhosts/staging/seed-config.sh && chmod +x /var/www/vhosts/staging/seed-config.sh" ]
            - [ sh, -c, "set -eu; export GITHUB_TOKEN='{{ ghub_token }}'; cd /var/www/vhosts/staging; /var/www/vhosts/staging/seed-install.sh; set -a; . /root/mysql.txt; set +a; export ADMIN_USER='{{ admin_user }}'; export ADMIN_EMAIL='{{ admin_email }}'; export ADMIN_PASS='{{ admin_pass }}'; export URL=https://'{{ droplet_name }}'; /var/www/vhosts/staging/seed-config.sh;" ]
      register: my_droplet

    - name: Show Droplet info
      ansible.builtin.debug:
        msg: |
          Droplet ID is {{ my_droplet.data.droplet.id }}
          IPv4 is {{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address }}

    - name: Tag a resource; creating the tag if it does not exist
      community.digitalocean.digital_ocean_tag:
        oauth_token: "{{ do_team_token }}"
        resource_id: "{{ my_droplet.data.droplet.id }}"
        name: pmpro-hosting-alpha
        state: present

    - name: Create a record using api token
      community.general.cloudflare_dns:
        zone: pmpro.site
        record: "{{ droplet_name }}"
        type: A
        proxied: true
        value: "{{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address }}"
        api_token: "{{ CF_TOKEN }}"

    - name: Send provisioning email via SES SMTP
      community.general.mail:
        host: "email-smtp.us-east-2.amazonaws.com"
        port: "2587"
        username: "{{ ses_uname }}"
        password: "{{ ses_passwd }}"
        secure: starttls
        to: "{{ admin_email }}"
        from: "Notifications@pmpromailer.com"
        subject: "New server created!"
        body: |
          Hello,

          Your server is ready.

          Name: {{ droplet_name }}
