---
# playbooks/create_droplet_from_snapshot.yml

- name: Create a Droplet from a Snapshot in a Specific Team
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - secrets.yml

  vars:
    # Name your droplet however you like
    droplet_name: my-snapshot-droplet-5

    # Choose your region and size slugs
    region: nyc3
    size: s-2vcpu-4gb

    # The snapshot identifier (UUID or slug)
    snapshot_id: "202344250"

    # Point this at a token that has access to your target team
    do_team_token: "{{ DIGITALOCEAN_TOKEN }}"

  tasks:
    - name: Create Droplet from Snapshot
      # Tell the module to use your team token via the env var
      community.digitalocean.digital_ocean_droplet:
        api_token: "{{ do_team_token }}"
        name: "{{ droplet_name }}"
        region: "{{ region }}"
        size: "{{ size }}"
        image: "{{ snapshot_id }}"
        ssh_keys: ['48536093']
        unique_name: true
        timeout: 500
        user_data: |  
          #cloud-config
          runcmd:
            - [ sh, -c, "hostnamectl set-hostname {{ droplet_name }}" ]
            - [ sh, -c, "wp db reset --yes --path=/var/www/html --allow-root || true" ]
            - [ sh, -c, "wp core install --url=https://{{ droplet_name }} --title='{{ site_title }}' --admin_user='{{ admin_user }}' --admin_password='{{ admin_pass }}' --admin_email='{{ admin_email }}' --path='/var/www/html' --allow-root" ]
            - [ sh, -c, "wp theme activate memberlite --path=/var/www/html --allow-root || true" ]
            - |
              #!/bin/bash
              set -euo pipefail
              # create restic env file for root
              cat > /root/.restic.env <<'EOF'
              RESTIC_REPOSITORY="s3:s3.us-east-2.amazonaws.com/pmpro-restic-test/{{ droplet_name }}"
              RESTIC_PASSWORD="Qwerty@123"
              EOF
              chmod 600 /root/.restic.env
              echo 'WROTE /root/.restic.env'
      register: my_droplet

    - name: Show Droplet info
      ansible.builtin.debug:
        msg: |
          Droplet ID is {{ my_droplet.data.droplet.id }}
          IPv4 is {{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address }}

    - name: Tag a resource; creating the tag if it does not exist
      community.digitalocean.digital_ocean_tag:
        oauth_token: "{{ do_team_token }}"
        resource_id: "{{ my_droplet.data.droplet.id }}"
        name: pmpro-hosting-alpha
        state: present

    - name: Create a record using api token
      community.general.cloudflare_dns:
        zone: pmpro.site
        record: "{{ droplet_name }}"
        type: A
        proxied: true
        value: "{{ (my_droplet.data.droplet.networks.v4 | selectattr('type', 'equalto', 'public')).0.ip_address }}"
        api_token: "{{ CF_TOKEN }}"

    - name: Send provisioning email via SES SMTP
      community.general.mail:
        host: "email-smtp.us-east-2.amazonaws.com"
        port: "2587"
        username: "{{ ses_uname }}"
        password: "{{ ses_passwd }}"
        secure: starttls
        to: "{{ admin_email }}"
        from: "Notifications@pmpromailer.com"
        subject: "New server created!"
        body: |
          Hello,

          Your server is ready.

          Name: {{ droplet_name }}
